// Create this file in lib/utils/job_categories.dart

class JobCategories {
  static const String otherOption = 'Others';

  static final List<String> categories = [
    'Babysitting Service - Babysitter/Nanny',
    'Beauty & Wellness - Eyelash Extensions & Henna Artist (Home Service)',
    'Beauty & Wellness - Hair Stylist, Makeup Artist, & Nail Technician (Home Service)',
    'Beauty & Wellness - Spa & Massage Therapies (Home Service)',
    'Cleaning Service - Home Cleaner',
    'Craft & Creative Service - Cake Baker (Order & Deliver to Customer)',
    'Craft & Creative Service - Gift Wrapper/Custom Hamper Maker/Surprise Delivery (Home Delivery)',
    'Elderly Care Service - Elderly Caregiver',
    'Errand Running - Personal Shopper/Runner',
    'Event Support - Event Crew (Setup/Decoration)',
    'Fitness & Wellness - Personal Trainer (Home Service)',
    'Fitness & Wellness - Yoga Instructor (Home Service)',
    'Food Delivery Service - Food Rider (Delivery Only)',
    'Food Service - Home Chef (Cook & Deliver)',
    'Health Care Service - Confinement Nanny',
    'Health Care Service - Postnatal Massage Therapist',
    'Laundry Service - Laundry Pickup/Drop',
    'Photography Service - Freelance Photographer',
    'Party Service - Party Decorator',
    'Pet Service - Pet Sitter/Dog Walker',
    'Tailoring Service - Tailor (Home Measurement & Delivery)',
    'Teaching/Tutoring Service - Art & Craft Teacher (Kids at Home)',
    'Teaching/Tutoring Service - Home Tutor',
    'Teaching/Tutoring Service - Music Teacher (Home Service)',
    'Teaching/Tutoring Service - Quran Teacher (Home Visit)',
    otherOption,
  ];
}

class Companies {
  static const String otherOption = 'Others';

  static final List<String> list = [
    'Ahmad Nazri Mansor (Tailor)',
    'Aura Dara Home Spa (Massage & Postnatal Care)',
    'Babysits.my (Babysitting Platform)',
    'Cassmira Balinese Spa (Spa Services)',
    'D\'Yunk Cafe (Home Chef / Food Delivery)',
    'Dobi Dyla (Laundry Service)',
    'Dottie Pet Shop (Pet Sitter)',
    'Eyqa Dania Wedding (Event Setup & Bridal Boutique)',
    'Faiqa Confinement Care Lady (Confinement Nanny Service)',
    'FitOne Studios (Personal Trainer)',
    'Global Art Jitra (Art & Craft Tutor)',
    'GoLearn (Tutor/Music/Yoga Platform)',
    'Grassroots Catering (Home Chef & Food Service)',
    'GrabFood (Food Delivery)',
    'Hair Zone Jitra (Hair Stylist)',
    'Hamper Bajet Kedah (Gift Hamper Service)',
    'Henna by Bihah (Henna Artist)',
    'Homebro Decor Empire (Party Decorator & Gift Hampers)',
    'House of Beauty & Health Jitra (Hair, Makeup & Nails)',
    'Inai Henna Jitra Art Kedah (Henna Artist)',
    'Just Fitness Jitra (Personal Trainer/Gym)',
    'Kaodim (Errand Running Platform)',
    'Kazri Photography (Freelance Photographer)',
    'Kedai Hamper Jitra (Gift Hampers)',
    'Kedai Kek Jitra (Cake Baker)',
    'Kelab Pengasuh Kedah (Babysitter Community)',
    'Kiddocare (Babysitting Platform)',
    'KN Confinement Care (Confinement Nanny)',
    'Lalamove (Errand Runner/Delivery Service)',
    'Local Home Kitchens (Home Chef)',
    'Makeup Artist Jenny Chua (Makeup Artist)',
    'My Magic Maid / Jia Yang Maid (Home Cleaning)',
    'Nisha Tailors (Tailor)',
    'NL Dobi (Laundry Service)',
    'Nittha Café (Cake Baker)',
    'One Jitra Solutions (Cleaning Services)',
    'Pantangplus (Confinement Nanny Platform)',
    'Party/Balloon Decorators - The.Balloons (Party Service)',
    'PetBacker (Pet Sitting Platform)',
    'Private Caregivers (Elderly Care - Freelance)',
    'Recommend.my (Freelance/Service Directory)',
    'Rider Freelancers (Food Delivery)',
    'Shurra Cleaning Services (Cleaning Services)',
    'Simanes.my (Cake Baker)',
    'Sitly (Babysitter/Nanny Platform)',
    'Superprof Malaysia (Tutoring Platform)',
    'Tabbyz Service (Pet Sitter via PetBacker)',
    'Thai Odyssey Jitra (Massage Service)',
    'The.Balloons (Party/Balloon Decoration)',
    'TutorKami (Quran Tutor Platform)',
    'Yeong Siew Chin Hairdresser (Hair Stylist)',
    otherOption,
  ];
}